/* This file is used to construct the final HTML document sent in the HTTP
 * response directly to the user's browser. It is best if any computation, or
 * any significant logic, is performed elsewhere, and complete arguments are
 * passed to the function. */

 import {
  Languages,
} from '../src/Enums/Languages';

export const renderDocument = ({
  appString,
  cssHash,
  description,
  fontLoaderString,
  language,
  preloadAndPreconnectLinks,
  reduxStateString,
  scripts,
  stylesheets,
  title,
  webpSnifferString,
}: {
  /* The React app, rendered to a string. */
  appString: string,
  /* The paths to each page's stylesheet. Generated by webpack-flush-chunks. */
  cssHash: string,
  /* The page description. */
  description: string,
  /* The code comprising the font loader. */
  fontLoaderString: string,
  /* The two-letter language code. Defaults to 'en' if nothing is provided. */
  language: Languages,
  /* An array of the rel="preload" and rel="preconnect" <link>s. */ 
  preloadAndPreconnectLinks: Array<string>,
  /* The server-generated Redux state, serialized into a JSON string. */
  reduxStateString: string,
  /* An array of the app scripts to inject into the document. */
  scripts: Array<string>,
  /* An array of the app styles to inject into the document. */
  stylesheets: Array<string>,
  /* The title of the page. */
  title: string,
  /* The code comprising the sniffer to check if the browser supports webp. */
  webpSnifferString: string,
}) => (
  `<!DOCTYPE html>
  <html lang="${language || 'en'}">
    <head>
      <title>${title}</title>
      <meta charset="utf-8">
      ${description}
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="theme-color" content="#ea5050">
      <meta name="msapplication-TileColor" content="#ea5050">
      <meta name="msapplication-TileImage" content="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/ms-icon-144x144_v2.png">
      <link rel="apple-touch-icon" sizes="57x57" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/apple-icon-57x57_v2.png">
      <link rel="apple-touch-icon" sizes="60x60" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/apple-icon-60x60_v2.png">
      <link rel="apple-touch-icon" sizes="72x72" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/apple-icon-72x72_v2.png">
      <link rel="apple-touch-icon" sizes="76x76" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/apple-icon-76x76_v2.png">
      <link rel="apple-touch-icon" sizes="114x114" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/apple-icon-114x114_v2.png">
      <link rel="apple-touch-icon" sizes="120x120" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/apple-icon-120x120_v2.png">
      <link rel="apple-touch-icon" sizes="144x144" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/apple-icon-144x144_v2.png">
      <link rel="apple-touch-icon" sizes="152x152" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/apple-icon-152x152_v2.png">
      <link rel="apple-touch-icon" sizes="180x180" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/apple-icon-180x180_v2.png">
      <link rel="icon" type="image/png" sizes="192x192" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/android-icon-192x192_v2.png">
      <link rel="icon" type="image/png" sizes="32x32" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/favicon-32x32_v2.png">
      <link rel="icon" type="image/png" sizes="96x96" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/favicon-96x96_v2.png">
      <link rel="icon" type="image/png" sizes="16x16" href="https://s3.eu-central-1.amazonaws.com/hellox/images/app-icons/favicon-16x16_v2.png">
      <link rel="manifest" href="/static/manifest.json">
      <script id="webpSniffer">${webpSnifferString}</script>
      ${stylesheets.join('\n')}
      ${preloadAndPreconnectLinks.join('\n')}
      <!-- scripts and styles added by framework below here -->
    </head>
    <body>
      <script async defer id="fontLoader">${fontLoaderString}</script>
      <script type="text/javascript" src="/static/vendor.js"></script>
      <div id="root">${appString}</div>
      ${cssHash}
      <script id="reduxState">window.REDUX_STATE=${reduxStateString}</script>
      ${scripts.join('\n')}
      <script async defer src="https://www.googletagmanager.com/gtag/js?id=UA-121190776-1"></script>
      <script async defer id="gtag">
        window.dataLayer=window.dataLayer||[];
        function gtag(){dataLayer.push(arguments);}
        gtag('js',new Date());
        gtag('config','UA-121190776-1');
      </script>
    </body>
  </html>`
);

export default renderDocument;